### ISSUE TITLE
mac下安装总是报错

### ISSUE THREAD

**Issue by bluesonny** [flutydeer/audio-slicer#10]
pywin32==306，环境 要求有的要求3.9 有的要求小于3.9，死活安装不成功

**Comment by flutydeer** [comment]
那个环境要求是我在 Windows 上 pip freeze 得到的，我没有 mac 设备，不知道 mac 上会安装不了。
试试 pip 安装 PySide6、numpy、soundfile、qdarktheme

**Comment by bluesonny** [comment]
所以没有在mac 上跑过是吧，
ERROR: No matching distribution found for pywin32==306
macos下没有这个
那能更新一份mac环境要求不

**Comment by bluesonny** [comment]
> 

我安装这个几个库，然后启动下是吧

**Comment by flutydeer** [comment]
你试试装完之后能不能跑起来，如果还缺什么库再安装

**Comment by bluesonny** [comment]
我试一试，感谢

**Comment by bluesonny** [comment]
注释掉 pywin32，然后版本换回3.10 就起来了。

**Comment by flutydeer** [comment]
谢谢你的反馈，我稍后修改一下环境要求和 README
