### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by JirachiBoi** [flutydeer/audio-slicer#14]
I get this error when trying to run slicer-gui.exe:

Unhandled exception in script
Failed to execute script 'slicer-gui' due to unhandled exception:
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed."

I tried uninstalling and re-installing NumPy, and it did not fix the error.

**Comment by flutydeer** [comment]
Are you using the latest version from Releases?

**Comment by JirachiBoi** [comment]
Yes

**Comment by flutydeer** [comment]
Did you extract all the files in the zip file?

**Comment by flutydeer** [comment]
The cause of this issue may be hard to find. Please try to clone this repository and install requirements.
