### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by not-lsj** [flutydeer/audio-slicer#17]
Can't the Windows version run anymore？

**Comment by flutydeer** [comment]
Please provide more details, such as the version of Windows

**Comment by not-lsj** [comment]
windows10

**Comment by flutydeer** [comment]
What happens after the app launches? Any screenshots or error messages?

**Comment by not-lsj** [comment]
The old version of the cut can not be cut, the new version of the cut has been loaded 0% No error message was reported

**Comment by flutydeer** [comment]
What format is the audio file? How long is the audio file? Can you provide your audio file for me to debug?

You can also try [OpenVPI's dataset-tools](https://github.com/openvpi/dataset-tools). It contains another implementation of audio slicer.

**Comment by not-lsj** [comment]
The audio was downloaded by Tik Tok, and the format was manually changed to. wav, It lasts about a minute.

**Comment by not-lsj** [comment]
Sorry, I seem to have found a problem, the video format cannot be changed manually, it needs to be converted to.wav
