### ISSUE TITLE
mp3 support

### ISSUE THREAD

**Issue by allandclive** [flutydeer/audio-slicer#20]

**Comment by TaiYouWeb** [comment]
请问何时可以添加这个功能啊，真的很需要mp3音频的输入以及输出。
我是不特别在乎音质的，mp3就够用，我现在都是手动来回转换格式，实在不便，如果能把像#21 一样的功能加进来就好了。

**Comment by flutydeer** [comment]
> 请问何时可以添加这个功能啊，真的很需要mp3音频的输入以及输出。
> 我是不特别在乎音质的，mp3就够用，我现在都是手动来回转换格式，实在不便，如果能把像#21 一样的功能加进来就好了。

最近比较忙，估计要等到七月才有空去检查那个 pr 的代码，可能要改一些东西才能发新版。另外真不推荐用 mp3 存人声，用 ogg 或者 aac 更好。

**Comment by TaiYouWeb** [comment]
> > 请问何时可以添加这个功能啊，真的很需要mp3音频的输入以及输出。
> > 我是不特别在乎音质的，mp3就够用，我现在都是手动来回转换格式，实在不便，如果能把像#21 一样的功能加进来就好了。
> 
> 最近比较忙，估计要等到七月才有空去检查那个 pr 的代码，可能要改一些东西才能发新版。另外真不推荐用 mp3 存人声，用 ogg 或者 aac 更好。

我另有用途，大小越小越好，格式越通用越好，音质倒无所谓，能听就行，所以MP3对我来说就够了。
那我七月以后再来看看。

**Comment by flutydeer** [comment]
支持输出 mp3 的版本已发布： [v1.3.0](https://github.com/flutydeer/audio-slicer/releases/tag/v1.3.0)
