### ISSUE TITLE
can i obtain each segment's timestamps?

### ISSUE THREAD

**Issue by hualizhou167** [flutydeer/audio-slicer#22]
Thank you for your great work. However, considering the unique nature of the data I'm working with, the automated output isn't precisely tailored to my needs. I'm interested in learning how to extract timestamps from the processed audio segments so that I can manually refine and merge them as necessary. Could you please provide guidance on how to achieve this? Your help is greatly appreciated!

**Comment by flutydeer** [comment]
See https://github.com/flutydeer/audio-slicer/discussions/18#discussioncomment-7452464

**Comment by hualizhou167** [comment]
Thank you for the information! I've taken a look at `slicer2.py` in the audio-slicer repository and found it helpful. I've implemented RMS to identify frames below a certain threshold, similar to what `Slicer.slice` appears to do. Additionally, I'm eager to explore  [the dataset-tools repo](https://github.com/openvpi/dataset-tools) further to enhance my project. Thanks again for your work!
