### ISSUE TITLE
無法開啟python-gui

### ISSUE THREAD

**Issue by Jeremyyen0978** [flutydeer/audio-slicer#25]
![image](https://github.com/user-attachments/assets/e0e48323-823e-492f-ba58-a7e15c86e0a2)
version:windows 10
python 3.11
I discovered that this code doesn't even have a file called python-gui.exe, now what?

**Comment by Jeremyyen0978** [comment]
New update:
![image](https://github.com/user-attachments/assets/d68414bd-6e39-40e3-899d-85f8ef576fe1)
The platform of audio slicer didn't pop out.

**Comment by flutydeer** [comment]
不是，我寻思着我打包的可执行文件也不是这个名字啊。你用的不是我的版本，出了问题应该去找给你软件的人
